name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**/*' # Only trigger on changes to the /docs folder

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add changes to git
        run: |
          git add -A
          git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main

      - name: Deploy to GitHub Pages
        run: |
          echo "Deploying to GitHub Pages..."
          git push origin main
